#pragma once

// Disable some RGB effects
#define DISABLE_RGB_MATRIX_BAND_VAL
#define DISABLE_RGB_MATRIX_BAND_SAT
#define DISABLE_RGB_MATRIX_BAND_PINWHEEL_VAL
#define DISABLE_RGB_MATRIX_BAND_PINWHEEL_SAT
#define DISABLE_RGB_MATRIX_BAND_SPIRAL_VAL
#define DISABLE_RGB_MATRIX_BAND_SPIRAL_SAT
#define DISABLE_RGB_MATRIX_CYCLE_PINWHEEL
#define DISABLE_RGB_MATRIX_RAINDROPS
#define DISABLE_RGB_MATRIX_JELLYBEAN_RAINDROPS
#define DISABLE_RGB_MATRIX_DUAL_BEACON
#define DISABLE_RGB_MATRIX_CYCLE_SPIRAL
#define DISABLE_RGB_MATRIX_CYCLE_OUT_IN
#define DISABLE_RGB_MATRIX_CYCLE_OUT_IN_DUAL
#define DISABLE_RGB_MATRIX_RAINBOW_BEACON
#define DISABLE_RGB_MATRIX_RAINBOW_PINWHEELS
#define DISABLE_RGB_MATRIX_DUAL_BEACON
#define DISABLE_RGB_MATRIX_BREATHING
#define DISABLE_RGB_MATRIX_HUE_BREATHING
#define DISABLE_RGB_MATRIX_HUE_PENDULUM
#define DISABLE_RGB_MATRIX_HUE_WAVE

/* #define RGB_MATRIX_FRAMEBUFFER_EFFECTS */
/* #define RGB_MATRIX_TYPING_HEATMAP_DECREASE_DELAY 50 */

#undef USB_LED_SCROLL_LOCK_SCANCODE
#undef USB_LED_COMPOSE_SCANCODE
                                  //
/* #define RGB_MATRIX_FRAMEBUFFER_EFFECTS */

#define RGB_MATRIX_KEYPRESSES
/* #define RGB_MATRIX_KEYRELEASES */
/* #define RGB_MATRIX_STARTUP_MODE RGB_MATRIX_CUSTOM_s4rch_reactive */
#define ENABLE_RGB_MATRIX_SOLID_REACTIVE_MULTIWIDE

